name: monitoring
on:
  push:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test ipv4 website status code
        run: sh websiteV4.sh
      - name: Test 
        run: wget -6 --no-check-certificate --spider -S "https://echbwien.at/" 2>&1
      - name: Test ipv6 website status code
        run: sh websiteV6.sh
      - name: Validate certificate
        run: sh certificate.sh
